import { Chapter } from "./yoga_sutras";

export const chapters : Chapter[] = [
  {
    id: 1,
    title: 'Samadhi Pada',
    title_jp: '三昧の章',
    description: 'On Contemplation',
    description_jp: '三昧について',
    summary: 'The first chapter, **Samadhi Pada**, delves into the nature of contemplation and absorption. It introduces the concept of yoga as a means to attain inner peace and enlightenment. The chapter explores various states of consciousness, from gross to subtle, culminating in the attainment of **asamprajñāta samādhi**, the highest state of consciousness where the mind transcends all dualities.',
    summary_jp: '第一章、**三昧の章**は、瞑想と没入の性質について探究します。ヨーガを内なる平安と悟りを得る手段として紹介し、粗大な意識から微細な意識に至るさまざまな状態を論じます。最終的には、心があらゆる二元性を超越する最高の意識状態である**非有想三昧（アサンプラジュニャータ・サマーディ）**の到達に至ります。',
    deep_dive: 'Chapter 1 of the Yoga Sutra, **Samādhi Pāda**, sets forth the philosophical core and soteriological vision of classical yoga. Patanjali opens by succinctly defining yoga as the cessation of mental fluctuations (citta-vritti-nirodhah), emphasizing that liberation is possible through mastery of the mind. The chapter carefully outlines the nature of these fluctuations—ranging from right knowledge and misconception to imagination, sleep, and memory—and describes how they bind the practitioner to suffering and ignorance of their true nature. Patanjali distinguishes between the changing contents of consciousness and the unchanging seer (Purusha), highlighting that recognizing this distinction is fundamental to spiritual progress. The text identifies obstacles such as doubt, carelessness, and restlessness, while prescribing systematic and sustained practice (abhyasa) combined with dispassion (vairagya) as essential disciplines for stilling the mind and advancing on the yogic path.\nThe latter half of the chapter delves deeply into the states of meditative absorption known as **samādhi**. Patanjali describes two principal forms: **samprajnata samādhi** (meditation with a focus or object, leading to refined states of concentration) and **asamprajnata samādhi** (absorption without any mental content, culminating in transcendence of the mind). The sutras explain that qualities such as faith, vigor, mindfulness, and sincere devotion to the Divine (Ishvara pranidhana) accelerate inner transformation. By integrating these principles, the practitioner gradually overcomes the veils of ignorance, experiences glimpses of pure awareness, and lays the groundwork for ultimate liberation (kaivalya). In essence, Chapter 1 offers a concise yet profound map of consciousness, meditation, and the transformative potential of yoga, setting the stage for the practical teachings that follow.',
    deep_dive_jp: '第1章「**サマーディ・パーダ**」は、古典ヨーガの哲学的核心と解脱へのヴィジョンを示します。パタンジャリは冒頭で、ヨーガを「心の働き（チッタ・ヴリッティ）の止滅」と簡潔に定義し、心の制御を通じて解脱が可能であることを強調します。本章では、正しい知識や誤解、想像、睡眠、記憶など多様な心の働きの性質を詳細に解説し、これらが修行者を苦しみと自己本質の無知に縛りつけることを示します。パタンジャリは、変化する意識の内容と不変の「見者」（プルシャ）を区別し、この洞察が霊的成長の基盤であることを明らかにします。疑念、怠惰、落ち着きのなさといった障害を挙げつつ、継続的な実践（アビヤーサ）と無執着（ヴァイラーギャ）を組み合わせて心を鎮め、ヨーガの道を進むための必須の規律として提示しています。\n章の後半では、瞑想的没入状態である「**サマーディ（三昧）**」の諸相を深く掘り下げます。パタンジャリは、対象に焦点を当てた「**サンプレクシャナタ・サマーディ**」と、あらゆる心的内容を超えた「**アサンプレクシャナタ・サマーディ**」という二つの主要な形態を説明し、これらが洗練された集中状態と心の超越へと導くことを示します。信仰、精力、気づき、そして神への誠実な献身（イーシュヴァラ・プラニダーナ）などの資質が内的変容を促進すると説かれています。これらの原理を統合することで、修行者は無知のヴェールを徐々に取り除き、純粋な気づきの一端を体験し、最終的な解脱（カイヴァリヤ）への基盤を築きます。第1章は、意識、瞑想、ヨーガの変容的可能性を簡潔かつ深遠に示し、続く実践的教えへの土台を築いています。'
  },
  {
    id: 2,
    title: 'Sadhana Pada',
    title_jp: '修行の章',
    description: 'On Practice',
    description_jp: '修行について',
    summary: 'The second chapter, **Sadhana Pada**, focuses on the practical aspects of yoga. It outlines the eight limbs of yoga, including ethical disciplines, physical postures, breath control, sense withdrawal, concentration, meditation, and absorption. The chapter emphasizes the importance of consistent practice and devotion in attaining yogic realization.',
    summary_jp: '第二章、**修行の章**は、ヨーガの実践的側面に焦点を当てます。ヨーガの八支則である倫理的規律、身体的姿勢、呼吸法、感覚の制御、集中、瞑想、そして三昧を含む段階を解説します。本章では、継続的な修習と献身がヨーガの悟りを得るために不可欠であることを強調しています。',
    deep_dive: 'Chapter 2, **Sādhana Pāda**, shifts from theory to practical methodology, outlining the concrete path for transforming the mind and overcoming suffering. Patanjali introduces **Kriya Yoga**—a path of disciplined action composed of tapas (austerity), svadhyaya (self-study), and Ishvara pranidhana (devotion to a higher reality)—as the means to weaken the causes of suffering (kleshas). The chapter analyzes the five fundamental kleshas: ignorance (avidya), egoism (asmita), attachment (raga), aversion (dvesha), and fear of death (abhinivesha), describing how they entangle the individual soul and perpetuate the cycle of suffering. By recognizing and attenuating these obstacles through right action and awareness, the aspirant creates the conditions for inner freedom.\nBuilding on this, Patanjali delineates the **eight limbs of yoga (ashtanga yoga)**, providing a systematic and holistic approach to self-realization. These limbs—yama (ethical restraints), niyama (observances), asana (posture), pranayama (breath control), pratyahara (withdrawal of senses), dharana (concentration), dhyana (meditation), and samadhi (absorption)—address all layers of the human experience, from external behavior to the deepest states of consciousness. The chapter explains how ethical living, discipline, and meditative practices purify the mind, reduce suffering, and ultimately lead to direct experience of the true Self. In essence, Sādhana Pāda serves as a practical manual for yogic living, guiding the practitioner step by step from bondage toward liberation.',
    deep_dive_jp: '第2章「**サーダナ・パーダ**」は、理論から実践へと焦点を移し、心の変容と苦しみの克服のための具体的な道筋を示します。パタンジャリは、苦しみの原因（クレーシャ）を弱めるための方法として、**クリヤ・ヨーガ**（タパス〈苦行〉、スヴァディヤーヤ〈自己学習〉、イーシュヴァラ・プラニダーナ〈至高存在への献身〉）を紹介します。五つの根本的なクレーシャ――無知（アヴィディヤー）、我執（アスミタ）、執着（ラーガ）、嫌悪（ドヴェーシャ）、死への恐れ（アビニヴェーシャ）――が分析され、これらが個の魂を束縛し、苦悩の輪廻を生み出すと説かれます。正しい行為と気づきを通じてこれらの障害を認識し、弱めることで、修行者は内的自由への条件を整えます。\nさらにパタンジャリは、**アシュタンガ・ヨーガ**（八支則）を体系的に示し、自己実現への包括的なアプローチを提供します。ヤマ（禁戒）、ニヤマ（勧戒）、アーサナ（座法）、プラーナーヤーマ（呼吸法）、プラティヤハーラ（感覚の制御）、ダーラナ（集中）、ディヤーナ（瞑想）、サマーディ（三昧）の八段階は、外面的な行動から最も深い意識状態に至るまで人間のあらゆる層をカバーしています。本章は、倫理的な生き方、規律、瞑想的実践が心を浄化し、苦しみを軽減し、最終的には真の自己の直接体験へと導くことを説きます。サーダナ・パーダは、束縛から解放への道を一歩一歩示すヨーガ実践の実用的な手引きとなっています。'
  },
  {
    id: 3,
    title: 'Vibhuti Pada',
    title_jp: '成就の章',
    description: 'On Attainments',
    description_jp: '成就について',
    summary: 'The third chapter, **Vibhuti Pada**, discusses the various attainments and powers that arise from yogic practice. It covers topics such as supernormal powers, psychic abilities, and the ultimate realization of the Self. The chapter underscores the transformative potential of yoga, which extends beyond mere physical and mental well-being to encompass spiritual awakening.',
    summary_jp: '第三章、**成就の章**は、ヨーガの修行によって得られるさまざまな成就と能力について論じます。超常的な力や霊的能力、そして自己の究極的な悟りを扱い、ヨーガが単なる身体的・精神的健康を超えて精神的覚醒をもたらす変容的可能性を強調しています。',
    deep_dive: 'Chapter 3, **Vibhūti Pāda**, explores the extraordinary capacities of consciousness that arise as a result of advanced yogic practice. Patanjali details the final three limbs of ashtanga yoga—**dharana** (concentration), **dhyana** (meditation), and **samadhi** (absorption)—and describes their sequential integration as **samyama**, a powerful technique for focusing the mind with precision and depth. Through mastery of samyama, the practitioner gains insight into the subtle realities of mind and nature, leading to the awakening of various **siddhis** (supernormal powers), such as heightened perception, intuitive knowledge, and even seemingly miraculous abilities. Patanjali systematically outlines these attainments not as ends in themselves, but as natural byproducts of disciplined spiritual practice.\nHowever, Patanjali repeatedly cautions against attachment to siddhis, warning that fascination with powers can distract the yogi from the true goal of yoga: liberation (kaivalya). The chapter emphasizes that these abilities, while real, ultimately become obstacles if they inflate the ego or reinforce worldly identification. Instead, the advanced practices of mental withdrawal, inner stillness, and deep concentration are presented as tools for transcending the limitations of ordinary consciousness and dissolving the seeds of karmic bondage. In essence, **Vibhūti Pāda** teaches that genuine yogic accomplishment is not measured by supernatural powers, but by the degree of inner freedom, clarity, and self-mastery attained through unwavering commitment to the path.',
    deep_dive_jp: '第3章「**ヴィブーティ・パーダ**」では、高度なヨーガ修習によって現れる意識の卓越した能力について探求します。パタンジャリはアシュタンガ・ヨーガの最後の三支――**ダーラナ**（集中）、**ディヤーナ**（瞑想）、**サマーディ**（三昧）――を詳述し、これらを連続的に統合する「**サンヤマ（総合的集中）**」の技法を解説します。サンヤマの熟達により、修行者は心と自然の微細な現実を洞察し、卓越した認識力や直観的知識、さらには奇跡的とも思える能力（シッディ）が目覚めます。パタンジャリは、これらの成就を目的そのものではなく、規律ある精神修行の自然な副産物として体系的に示しています。\nしかし、パタンジャリはシッディへの執着に繰り返し警告を発し、能力への魅了がヨーガの真の目的である解脱（カイヴァリヤ）から修行者を逸らす危険を指摘します。これらの能力は現実であっても、エゴを膨張させたり世俗的同一化を強めたりする場合は障害となります。代わりに、心の離脱、内的静寂、深い集中の高度な実践が、通常の意識の限界を超え、カルマの種子を解消するための手段として示されています。要するに、**ヴィブーティ・パーダ**は、真のヨーガの成就は超常的な力ではなく、揺るぎない修行によって得られる内的自由、明晰さ、自己統御の度合いによって測られることを教えています。'
  },
  {
    id: 4,
    title: 'Kaivalya Pada',
    title_jp: '解脱の章',
    description: 'On Liberation',
    description_jp: '解脱について',
    summary: 'The final chapter, **Kaivalya Pada**, delves into the state of liberation or **kaivalya**. It explores the nature of the Self, the dissolution of the ego, and the attainment of pure consciousness. The chapter culminates in the realization of the unity of the individual Self with the universal Self, marking the pinnacle of yogic attainment.',
    summary_jp: '第四章、**解脱の章**は、解脱（カイヴァリヤ）の境地を探究します。自己の本質、我の解体、そして純粋な意識の獲得を論じ、個別の自己と普遍的自己の統一の実現をもってヨーガの究極的到達点を示します。',
    deep_dive: 'Chapter 4, **Kaivalya Pāda**, brings the journey of the Yoga Sutra to its philosophical and experiential culmination. Patanjali examines the nature of liberation (**kaivalya**), delving into how consciousness becomes disentangled from material existence and the cycle of karma. The chapter explores the origins of siddhis (supernormal powers), clarifying that these can arise not only from yogic practices but also from birth, herbs, or intense austerity. Yet, the focus remains on understanding the mechanics of transformation: how past impressions (samskaras) and actions (karma) perpetuate the illusion of individuality. Patanjali explains that as the mind is purified and fluctuations subside, the practitioner comes to realize the true nature of the Self as distinct from the mind, senses, and external world.\nThe final teachings emphasize that true liberation is the complete and irreversible separation of Purusha (pure consciousness) from Prakriti (nature/matter). When all residual karma is exhausted and the mind ceases to color perception, the yogi abides in their own intrinsic luminosity—beyond suffering, change, or limitation. Patanjali asserts that this **kaivalya**, or absolute freedom, is not annihilation but the full realization of the Self’s eternal, unconditioned nature. Chapter 4 thus offers a sophisticated map of consciousness and liberation, affirming that the ultimate purpose of yoga is not powers or experiences, but the total freedom and isolation (in the positive sense) of pure awareness itself.',
    deep_dive_jp: '第4章「**カイヴァリヤ・パーダ**」は、『ヨーガ・スートラ』の哲学的かつ体験的な到達点を示します。パタンジャリは解脱（**カイヴァリヤ**）の本質を探求し、意識がいかに物質的存在やカルマの循環から解き放たれるかを論じます。本章ではシッディ（超常的能力）の起源にも触れ、これらがヨーガ修行のみならず、生得的資質や薬草、厳しい苦行など多様な要因によっても生じることを明らかにします。しかし、焦点は変容の仕組みの理解にあり、過去の印象（サンスカーラ）や行為（カルマ）が個の錯覚を維持し続ける様子を解説します。心が浄化され揺らぎが消滅すると、修行者は自己（真我）が心や感覚、外界とは本質的に異なる存在であることを悟ります。\n最終的な教えは、真の解脱とはプルシャ（純粋意識）がプラクリティ（自然・物質）から完全かつ不可逆的に分離されることであると強調します。すべての残存カルマが尽き、心の作用が認識を曇らせなくなったとき、ヨーギーは苦しみや変化、制限を超えた本来の輝きに安住します。パタンジャリは、この**カイヴァリヤ**――絶対的自由――が消滅ではなく、自己の永遠かつ無条件の本性の完全な実現であると明言します。第4章は意識と解放の精緻な地図を示し、ヨーガの究極的目的が能力や体験ではなく、「純粋な気づき」そのものの徹底した自由にあることを示しています。'
  },
];
