import { Chapter } from "./yoga_sutras";

export const chapters : Chapter[] = [
  {
    id: 1,
    title: 'Samadhi Pada',
    title_jp: '三昧の章',
    description: 'On Contemplation',
    description_jp: '三昧について',
    summary: 'The first chapter, **Samadhi Pada**, delves into the nature of contemplation and absorption. It introduces the concept of yoga as a means to attain inner peace and enlightenment. The chapter explores various states of consciousness, from gross to subtle, and culminates in the attainment of **asamprajñāta samādhi**, the highest state of consciousness where the mind transcends all dualities.',
    summary_jp: '第一章、**三昧の章**は、冥想と吸収の性質について探究します。ヨーガを内心の平和と啓示に至る手段として紹介します。この章では、粗い意識から微細な意識までさまざまな意識の状態を探究し、最終的には**非有想三昧（アサンプラジュニャータ・サマーディ）**に至る、すべての二重性を超越する最高の意識の状態を達成します。',
    deep_dive: 'Chapter 1 of the Yoga Sutra, **Samādhi Pāda**, sets forth the philosophical core and soteriological vision of classical yoga. Patanjali opens by succinctly defining yoga as the cessation of mental fluctuations (citta-vritti-nirodhah), emphasizing that liberation is possible through mastery of the mind. The chapter carefully outlines the nature of these fluctuations—ranging from right knowledge and misconception to imagination, sleep, and memory—and describes how they bind the practitioner to suffering and ignorance of their true nature. Patanjali distinguishes between the changing contents of consciousness and the unchanging seer (Purusha), highlighting that recognizing this distinction is fundamental to spiritual progress. The text identifies obstacles such as doubt, carelessness, and restlessness, while prescribing systematic and sustained practice (abhyasa) combined with dispassion (vairagya) as essential disciplines for stilling the mind and progressing on the yogic path.\nThe latter half of the chapter delves deeply into the states of meditative absorption known as **samādhi**. Patanjali describes two principal forms: **samprajnata samādhi** (meditation with a focus or object, leading to refined states of concentration) and **asamprajnata samādhi** (absorption without any mental content, culminating in transcendence of the mind). The sutras explain that qualities such as faith, vigor, mindfulness, and a sincere devotion to the Divine (Ishvara pranidhana) accelerate inner transformation. By integrating these principles, the practitioner gradually overcomes the veils of ignorance, experiencing glimpses of pure awareness and laying the groundwork for ultimate liberation (kaivalya). In essence, Chapter 1 offers a concise yet profound map of consciousness, meditation, and the transformative potential of yoga, setting the stage for the practical teachings that follow.',
    deep_dive_jp: '第1章「**サマーディ・パーダ**」は、クラシカル・ヨーガの哲学的核心と解脱へのヴィジョンを示す章です。パタンジャリは冒頭で、ヨーガを「心の働き（チッタ・ヴリッティ）の止滅」と定義し、心の制御を通じて真の自由（解脱）が可能であることを強調します。本章では、心の働きには正しい知識、誤解、想像、睡眠、記憶など様々な種類があり、それらが自己の本質を覆い苦しみの原因となることを説明します。また、変化し続ける心の内容（チッタ）と、不変の「見者」（プルシャ）を明確に区別し、この洞察が霊的成長に不可欠であると説きます。疑念や怠惰、落ち着きのなさといった障害を挙げつつ、「アビヤーサ（継続的な修習）」と「ヴァイラーギャ（無執着）」の二つを、心を鎮めるための根本的な実践として提示しています。\n章の後半では、深い瞑想の到達点である「**サマーディ（三昧）**」の諸相が詳細に語られます。パタンジャリは、対象を持つ「**サンプレクシャナタ・サマーディ**」と、あらゆる心的対象を超えた「**アサンプレクシャナタ・サマーディ**」という二つの主要な形態を説明し、これらが意識の精緻化と究極的な超越につながることを示します。さらに、信仰、精進、記憶、気づき、そして「イーシュヴァラ・プラニダーナ（至高なる存在への献身）」などの資質が、内的変容を加速させると述べられています。これらの教えを統合することで、実践者は無知のヴェールを取り除き、純粋な意識の一端を体験し、最終的な解脱（カイヴァリヤ）への道筋を歩み始めるのです。第1章は、意識・瞑想・ヨーガの変容的可能性を簡潔かつ深遠に示し、続く実践的な教えへの基盤を築いています。'
  },
  {
    id: 2,
    title: 'Sadhana Pada',
    title_jp: '修行の章',
    description: 'On Practice',
    description_jp: '修行について',
    summary: 'The second chapter, **Sadhana Pada**, focuses on the practical aspects of yoga. It outlines the eight limbs of yoga, including ethical disciplines, physical postures, breath control, sense withdrawal, concentration, meditation, and absorption. The chapter emphasizes the importance of consistent practice and devotion in attaining yogic realization.',
    summary_jp: '第二章、**修行の章**は、ヨーガの実践的な側面に焦点を当てます。ヨーガの八つの段階、倫理的 Discipline、身体的 Discipline、呼吸法、感覚の制御、集中、瞑想、吸収を含む、を解説します。この章では、継続的な修習と devotion がヨーガの実現に不可欠であることを強調します。',
    deep_dive: 'Chapter 2, **Sādhana Pāda**, shifts from theory to practical methodology, outlining the concrete path for transforming the mind and overcoming suffering. Patanjali introduces **Kriya Yoga**—a path of disciplined action composed of tapas (austerity), svadhyaya (self-study), and Ishvara pranidhana (devotion to a higher reality)—as the means to weaken the causes of suffering (kleshas). The chapter analyzes the five fundamental kleshas: ignorance (avidya), egoism (asmita), attachment (raga), aversion (dvesha), and fear of death (abhinivesha), describing how they entangle the individual soul and perpetuate the cycle of suffering. By recognizing and attenuating these obstacles through right action and awareness, the aspirant creates the conditions for inner freedom.\nBuilding on this, Patanjali delineates the **eight limbs of yoga (ashtanga yoga)**, providing a systematic and holistic approach to self-realization. These limbs—yama (ethical restraints), niyama (observances), asana (posture), pranayama (breath control), pratyahara (withdrawal of senses), dharana (concentration), dhyana (meditation), and samadhi (absorption)—address all layers of the human experience, from external behavior to the deepest states of consciousness. The chapter explains how ethical living, discipline, and meditative practices purify the mind, reduce suffering, and ultimately lead to direct experience of the true Self. In essence, Sādhana Pāda serves as a practical manual for yogic living, guiding the practitioner step by step from bondage toward liberation.',
    deep_dive_jp: '第2章「**サーダナ・パーダ**」は、理論から実践へと焦点を移し、心の変容と苦しみの克服のための具体的な道筋を示します。パタンジャリは、苦しみの根源（クレーシャ）を弱めるための方法として、**クリヤ・ヨーガ**（タパス〈苦行〉、スヴァディヤーヤ〈自己学習〉、イーシュヴァラ・プラニダーナ〈至高存在への献身〉）を紹介します。ここで五つの根本的なクレーシャ――無知（アヴィディヤー）、我執（アスミタ）、執着（ラーガ）、嫌悪（ドヴェーシャ）、死への恐れ（アビニヴェーシャ）――が分析され、これらが個の魂を束縛し、苦悩の輪廻を引き起こすと説かれます。これらの障害を正しい行為と気づきによって見極め、徐々に取り除いていくことで、内的な自由への道が開かれます。\nさらにパタンジャリは、**アシュタンガ・ヨーガ**（八支則）を体系的に提示し、自己実現への全体的なアプローチを与えます。ヤマ（禁戒）、ニヤマ（勧戒）、アーサナ（座法）、プラーナーヤーマ（呼吸法）、プラティヤハーラ（感覚の制御）、ダーラナ（集中）、ディヤーナ（瞑想）、サマーディ（三昧）の八段階は、外面的な行動から最も深い意識の状態に至るまで人間存在のあらゆる層をカバーしています。本章では、倫理的な生き方、自己鍛錬、瞑想的実践によって心が浄化され、苦しみが減少し、最終的には真の自己の直接体験に導かれることが説かれます。サーダナ・パーダは、束縛から解放へと一歩一歩導く、ヨーガ実践の実践的な手引きとして機能しています。'
  },
  {
    id: 3,
    title: 'Vibhuti Pada',
    title_jp: '成就の章',
    description: 'On Attainments',
    description_jp: '成就について',
    summary: 'The third chapter, **Vibhuti Pada**, discusses the various attainments and powers that arise from yogic practice. It covers topics such as supernormal powers, psychic abilities, and the ultimate realization of the Self. The chapter underscores the transformative potential of yoga, which goes beyond mere physical and mental well-being to encompass spiritual awakening.',
    summary_jp: '第三章、**成就の章**は、ヨーガの修行から生じるさまざまな達成と能力について探究します。超常能力、 psychic 能力、そして自己の究極的な realization を含む、様々なトピックを扱います。この章では、ヨーガの変容的な可能性を強調します。それは単なる身体的や心的健康を超えた、精神的な覚醒を包含するものです。',
    deep_dive: 'Chapter 3, **Vibhūti Pāda**, explores the extraordinary capacities of consciousness that arise as a result of advanced yogic practice. Patanjali details the final three limbs of ashtanga yoga—**dharana** (concentration), **dhyana** (meditation), and **samadhi** (absorption)—and describes their sequential integration as **samyama**, a powerful technique for focusing the mind with precision and depth. Through mastery of samyama, the practitioner gains insight into the subtle realities of mind and nature, leading to the awakening of various **siddhis** (supernormal powers), such as heightened perception, intuitive knowledge, and even seemingly miraculous abilities. Patanjali systematically outlines these attainments not as ends in themselves, but as natural byproducts of disciplined spiritual practice.\nHowever, Patanjali repeatedly cautions against attachment to siddhis, warning that fascination with powers can distract the yogi from the true goal of yoga: liberation (kaivalya). The chapter emphasizes that these abilities, while real, are ultimately obstacles if they inflate the ego or reinforce worldly identification. Instead, the advanced practices of mental withdrawal, inner stillness, and deep concentration are presented as tools for transcending the limitations of ordinary consciousness and dissolving the seeds of karmic bondage. In essence, **Vibhūti Pāda** teaches that genuine yogic accomplishment is not measured by supernatural powers, but by the degree of inner freedom, clarity, and self-mastery attained through unwavering commitment to the path.',
    deep_dive_jp: '第3章「**ヴィブーティ・パーダ**」では、ヨーガの高度な修習によって現れる意識の卓越した力について論じられます。パタンジャリはアシュタンガ・ヨーガの最後の三支――**ダーラナ**（集中）、**ディヤーナ**（瞑想）、**サマーディ**（三昧）――の実践と、その三つを統合した「**サンヤマ（総合的集中）**」の技法を詳しく解説します。サンヤマの熟達によって、修行者は心や自然の微細な現実を洞察し、卓越した認識力や直観的な知恵、さらには超常的な能力（シッディ）などが自然に現れると説かれます。パタンジャリは、これらの能力が精神的な修行の自然な副産物であり、最終目標ではないことを体系的に述べています。\nしかしパタンジャリは、シッディへの執着に対して繰り返し警告を発します。これらの能力に心を奪われることで、ヨーギーは本来のヨーガの目的――すなわち解脱（カイヴァリヤ）――から逸れてしまう危険があると説きます。これらの能力が現実であっても、エゴを増長させたり、世俗的な自己同一化を強めたりするならば、それ自体が障害となるのです。真のヨーガの達成とは、超常的な力によるのではなく、心の自由・明晰さ・自己統御の深さによって測られるものであると、この章は強調します。**ヴィブーティ・パーダ**は、揺るぎない修行によって、意識の限界を超え、カルマの束縛を解消するための内的技法の本質を説いています。'
  },
  {
    id: 4,
    title: 'Kaivalya Pada',
    title_jp: '解脱の章',
    description: 'On Liberation',
    description_jp: '解脱について',
    summary: 'The final chapter, **Kaivalya Pada**, delves into the state of liberation or **kaivalya**. It explores the nature of the Self, the dissolution of the ego, and the attainment of pure consciousness. The chapter culminates in the realization of the unity of the individual Self with the universal Self, marking the pinnacle of yogic attainment.',
    summary_jp: '第四章、解脱の章は、解脱（カイヴァリヤ）の状態について探究します。自己の性質、我の解体、そして純粋な意識の達成を探究します。この章では、個人の自己と普遍的な自己の統一を実現し、ヨーガの達成の頂点に達します。',
    deep_dive: 'Chapter 4, **Kaivalya Pāda**, brings the journey of the Yoga Sutra to its philosophical and experiential culmination. Patanjali examines the nature of liberation (**kaivalya**), delving into how consciousness becomes disentangled from material existence and the cycle of karma. The chapter explores the origins of siddhis (supernormal powers), clarifying that these can arise not only from yogic practices, but also from birth, herbs, or intense austerity. Yet, the focus is on understanding the mechanics of transformation: how past impressions (samskaras) and actions (karma) perpetuate the illusion of individuality. Patanjali explains that as the mind is purified and the fluctuations subside, the practitioner comes to realize the true nature of the Self as distinct from the mind, senses, and external world.\nThe final teachings emphasize that true liberation is the complete and irreversible separation of Purusha (pure consciousness) from Prakriti (nature/matter). When all residual karma is exhausted and the mind ceases to color perception, the yogi abides in their own intrinsic luminosity—beyond suffering, change, or limitation. Patanjali asserts that this **kaivalya**, or absolute freedom, is not an annihilation but the full realization of the Self’s eternal, unconditioned nature. Chapter 4 thus offers a sophisticated map of consciousness and liberation, affirming that the ultimate purpose of yoga is not powers or experiences, but the total freedom and isolation (in the positive sense) of pure awareness itself.',
    deep_dive_jp: '第4章「**カイヴァリヤ・パーダ**」は、『ヨーガ・スートラ』全体の哲学的かつ実践的な到達点を示します。パタンジャリは、解脱（**カイヴァリヤ**）の本質について深く探求し、意識がいかにして物質的存在やカルマの循環から解放されるのかを論じます。本章では、シッディ（超常的な力）の起源についても触れられ、それがヨーガ修行のみならず、生得的資質や薬草、厳しい苦行など様々な要因によって生じ得ることを説明します。しかし、重要なのは変容の仕組みを理解することであり、過去の印象（サンスカーラ）や行為（カルマ）が個としての錯覚を維持し続ける様子が解説されます。心が浄化され、揺らぎが止滅したとき、修行者は自己（真我）が心や感覚、外的世界とは本質的に異なる存在であることを体験的に悟ります。\nこの最終章では、真の解脱とは、プルシャ（純粋意識）がプラクリティ（自然・物質）から完全かつ不可逆的に分離されることであると強調されます。あらゆる残存するカルマが尽き、心の作用がもはや認識を曇らせなくなったとき、ヨーギーは苦しみや変化、制限を超えた本来の輝き（純粋な自己）に安住します。パタンジャリは、この**カイヴァリヤ**――絶対的自由――が消滅ではなく、自己の永遠かつ無条件の本性を完全に実現することであると明言します。第4章は、意識と解放の精緻な地図を描き、ヨーガの究極的な目的が能力や体験ではなく、「純粋な気づき」そのものの徹底した自由にあることを明らかにしています。'
  },
];
