import { yoga_sutra_terms } from "./terminology";

interface Reference {
    chapter: number;
    verse: number;
}

interface Terminology {
    term: string;
    refs: Reference[];
    definition: string;
    definition_jp: string;
    insights: string;
    insights_jp: string;
}

export const yoga_sutra_terminology : Terminology[] = [
    { term: "Abhinivesa", ...yoga_sutra_terms.Abhinivesa },
    { term: "Abhyasa", ...yoga_sutra_terms.Abhyasa },
    { term: "Ahamkara", ...yoga_sutra_terms.Ahamkara },
    { term: "Ahimsa", ...yoga_sutra_terms.Ahimsa },
    { term: "Agama", ...yoga_sutra_terms.Agama },
    { term: "Alambana", ...yoga_sutra_terms.Alambana },
    { term: "Anubhava", ...yoga_sutra_terms.Anubhava },
    { term: "Anumana", ...yoga_sutra_terms.Anumana },
    { term: "Antaraya", ...yoga_sutra_terms.Antaraya },
    { term: "Aparigraha", ...yoga_sutra_terms.Aparigraha },
    { term: "Asana", ...yoga_sutra_terms.Asana },
    { term: "Asmita", ...yoga_sutra_terms.Asmita },
    { term: "Asmitarupa", ...yoga_sutra_terms.Asmitarupa },
    { term: "Astanga", ...yoga_sutra_terms.Astanga },
    { term: "Asteya", ...yoga_sutra_terms.Asteya },
    { term: "Atha", ...yoga_sutra_terms.Atha },
    { term: "Atman", ...yoga_sutra_terms.Atman },
    { term: "Avidya", ...yoga_sutra_terms.Avidya },
    { term: "Brahmacarya", ...yoga_sutra_terms.Brahmacarya },
    { term: "Buddhi", ...yoga_sutra_terms.Buddhi },
    { term: "Citta", ...yoga_sutra_terms.Citta },
    { term: "Dharana", ...yoga_sutra_terms.Dharana },
    { term: "Dharma", ...yoga_sutra_terms.Dharma },
    { term: "Dharmamegha", ...yoga_sutra_terms.Dharmamegha },
    { term: "Dhyana", ...yoga_sutra_terms.Dhyana },
    { term: "Duhkha", ...yoga_sutra_terms.Duhkha },
    { term: "Dvesa", ...yoga_sutra_terms.Dvesa },
    { term: "Ekagrata Parinama", ...yoga_sutra_terms.Ekagrata_Parinama },
    { term: "Guna", ...yoga_sutra_terms.Guna },
    { term: "Isvara", ...yoga_sutra_terms.Isvara },
    { term: "Isvara-Pranidhana", ...yoga_sutra_terms.Isvara_Pranidhana },
    { term: "jivanmuktas", ...yoga_sutra_terms.jivanmuktas },
    { term: "Jnana", ...yoga_sutra_terms.Jnana },
    { term: "Kaivalya", ...yoga_sutra_terms.Kaivalya },
    { term: "Karma", ...yoga_sutra_terms.Karma },
    { term: "Klesa", ...yoga_sutra_terms.Klesa },
    { term: "Kriya", ...yoga_sutra_terms.Kriya },
    { term: "Manas", ...yoga_sutra_terms.Manas },
    { term: "Mukta", ...yoga_sutra_terms.Mukta },
    { term: "Nidra", ...yoga_sutra_terms.Nidra },
    { term: "Nirbija", ...yoga_sutra_terms.Nirbija },
    { term: "Nirvikalpa", ...yoga_sutra_terms.Nirvikalpa },
    { term: "Nirodha Parinama", ...yoga_sutra_terms.Nirodha_Parinama },
    { term: "Nirvicara", ...yoga_sutra_terms.Nirvicara },
    { term: "Nirvicara Samadhi", ...yoga_sutra_terms.Nirvicara_Samadhi },
    { term: "Nirvitarka", ...yoga_sutra_terms.Nirvitarka },
    { term: "Nirvitarka Samadhi", ...yoga_sutra_terms.Nirvitarka_Samadhi },
    { term: "Niyama", ...yoga_sutra_terms.Niyama },
    { term: "OM", ...yoga_sutra_terms.OM },
    { term: "Pada", ...yoga_sutra_terms.Pada },
    { term: "Parinama", ...yoga_sutra_terms.Parinama },
    { term: "Prajna", ...yoga_sutra_terms.Prajna },
    { term: "Prakrti", ...yoga_sutra_terms.Prakrti },
    { term: "Pramana", ...yoga_sutra_terms.Pramana },
    { term: "Prana", ...yoga_sutra_terms.Prana },
    { term: "Pranayama", ...yoga_sutra_terms.Pranayama },
    { term: "Pranidhana", ...yoga_sutra_terms.Pranidhana },
    { term: "Pratipaksha", ...yoga_sutra_terms.Pratipaksha },
    { term: "Pratipaksha Bhavana", ...yoga_sutra_terms.Pratipaksha_bhavana },
    { term: "Pratyahara", ...yoga_sutra_terms.Pratyahara },
    { term: "Pratyaksha", ...yoga_sutra_terms.Pratyaksha },
    { term: "Pratyakshapratyaksha", ...yoga_sutra_terms.Pratyakshapratyaksha },
    { term: "Pratyaya", ...yoga_sutra_terms.Pratyaya },
    { term: "Purusa", ...yoga_sutra_terms.Purusa },
    { term: "Raga", ...yoga_sutra_terms.Raga },
    { term: "Rajas", ...yoga_sutra_terms.Rajas },
    { term: "Sabijah", ...yoga_sutra_terms.Sabijah },
    { term: "Samadhi", ...yoga_sutra_terms.Samadhi },
    { term: "Samadhi  Parinama", ...yoga_sutra_terms.Samadhi_Parinama },
    { term: "Samapatti", ...yoga_sutra_terms.Samapatti },
    { term: "Samprajnata", ...yoga_sutra_terms.Samprajnata },
    { term: "Samprajnata Samadhi", ...yoga_sutra_terms.Samprajnata_Samadhi },
    { term: "Samsara", ...yoga_sutra_terms.Samsara },
    { term: "Samsaya", ...yoga_sutra_terms.Samsaya },
    { term: "Samskara", ...yoga_sutra_terms.Samskara },
    { term: "Samtosa", ...yoga_sutra_terms.Samtosa },
    { term: "Samyama", ...yoga_sutra_terms.Samyama },
    { term: "Samyoga", ...yoga_sutra_terms.Samyoga },
    { term: "Sattva", ...yoga_sutra_terms.Sattva },
    { term: "Satya", ...yoga_sutra_terms.Satya },
    { term: "Sauca", ...yoga_sutra_terms.Sauca },
    { term: "Savicara", ...yoga_sutra_terms.Savicara },
    { term: "Savicara Samadhi", ...yoga_sutra_terms.Savicara_Samadhi },
    { term: "Savitarka", ...yoga_sutra_terms.Savitarka },
    { term: "Savitarka Samadhi", ...yoga_sutra_terms.Savitarka_Samadhi },
    { term: "Siddhi", ...yoga_sutra_terms.Siddhi },
    { term: "Siddhas", ...yoga_sutra_terms.Siddhas },
    { term: "Smrti", ...yoga_sutra_terms.Smrti },
    { term: "Sraddha", ...yoga_sutra_terms.Sraddha },
    { term: "Sthira", ...yoga_sutra_terms.Sthira },
    { term: "Sukha", ...yoga_sutra_terms.Sukha },
    { term: "Sukshma", ...yoga_sutra_terms.Sukshma },
    { term: "Svadhyaya", ...yoga_sutra_terms.Svadhyaya },
    { term: "Svapna", ...yoga_sutra_terms.Svapna },
    { term: "Tamas", ...yoga_sutra_terms.Tamas },
    { term: "Tapas", ...yoga_sutra_terms.Tapas },
    { term: "Tattva", ...yoga_sutra_terms.Tattva },
    { term: "Turiya", ...yoga_sutra_terms.Turiya },
    { term: "Turiyatita", ...yoga_sutra_terms.Turiyatita },
    { term: "Vairagya", ...yoga_sutra_terms.Vairagya },
    { term: "Vasana", ...yoga_sutra_terms.Vasana },
    { term: "Vasikara", ...yoga_sutra_terms.Vasikara },
    { term: "Vijnana", ...yoga_sutra_terms.Vijnana },
    { term: "Vikalpa", ...yoga_sutra_terms.Vikalpa },
    { term: "Viparyaya", ...yoga_sutra_terms.Viparyaya },
    { term: "Virya", ...yoga_sutra_terms.Virya },
    { term: "Viveka", ...yoga_sutra_terms.Viveka },
    { term: "Vrtti", ...yoga_sutra_terms.Vrtti },
    { term: "Vyadhi", ...yoga_sutra_terms.Vyadhi },
    { term: "Yama", ...yoga_sutra_terms.Yama },
    { term: "Yoga", ...yoga_sutra_terms.Yoga }
];
